// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2PT0rSNBYSPqIVb_SDeKH8pdJJtcwJAM',
    appId: '1:257611940713:web:42d21724e97bcce649f3f8',
    messagingSenderId: '257611940713',
    projectId: 'ecommerceapp-cff36',
    authDomain: 'ecommerceapp-cff36.firebaseapp.com',
    storageBucket: 'ecommerceapp-cff36.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTNUJ5uR5cfan7NJQdI8u_t2ZiVRBQBpE',
    appId: '1:257611940713:android:a215b9689730cc7149f3f8',
    messagingSenderId: '257611940713',
    projectId: 'ecommerceapp-cff36',
    storageBucket: 'ecommerceapp-cff36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsuP3LYiRZgml_bBgyRhaKALAEW7JmlYU',
    appId: '1:257611940713:ios:505dd199f158c59349f3f8',
    messagingSenderId: '257611940713',
    projectId: 'ecommerceapp-cff36',
    storageBucket: 'ecommerceapp-cff36.firebasestorage.app',
    androidClientId: '257611940713-9fjk4jbscfv5351apgnhtp5i4u3esg6s.apps.googleusercontent.com',
    iosClientId: '257611940713-0o7n24tvk19jrfjt5gihqvo6fklef6m8.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

}